[package]
name = "circle-plonk-circom-quotient"
version = "0.1.0"
edition = "2021"

[dependencies]
stwo-prover.workspace = true
circle-plonk-circom-hints.workspace = true
serde_json.workspace = true
serde.workspace = true