[workspace]
members = ["poseidon31", "circle", "channel"]
resolver = "2"

[workspace.dependencies]
poseidon2-m31 = { git = "https://github.com/Bitcoin-Wildlife-Sanctuary/poseidon2-m31.git" }
serde_json = "1.0.133"
rand = "0.8.5"
rand_chacha = "0.3.1"
ark-std = "0.4.0"
stwo-prover = { git = "https://github.com/Bitcoin-Wildlife-Sanctuary/stwo", branch = "move-mult-in-plonk" }