[package]
name = "circle-plonk-circom-circle"
version = "0.1.0"
edition = "2021"

[dependencies]
stwo-prover.workspace = true
serde_json.workspace = true
rand.workspace = true
rand_chacha.workspace = true
ark-std.workspace = true
log = "0.4.22"